repos:
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: '8e0d199'
    hooks:
    -   id: prettier
        types: [javascript]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'd048c4f'
    hooks:
    -   id: eslint